import { useEffect, useRef, useState } from 'react';
import maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';

type Props = {
  latitude: number;
  longitude: number;
  onChange: (latitude: number, longitude: number) => void;
};

// Generated by scripts/build-plaster-style.js.
const STYLE_URL = '/map-styles/plaster.json';
const PIN_ZOOM = 17;
const OVERVIEW_ZOOM = 1.5;
const SATELLITE_SOURCE_ID = 'picker-satellite';
const SATELLITE_LAYER_ID = 'picker-satellite';
// Esri World Imagery: check Esri's terms of use before relying on it in production.
const SATELLITE_SOURCE: maplibregl.RasterSourceSpecification = {
  type: 'raster',
  tiles: ['https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'],
  tileSize: 256,
  maxzoom: 19,
  attribution: 'Imagery © Esri, Maxar, Earthstar Geographics',
};

const hasCoordinates = (latitude: number, longitude: number) =>
  Number.isFinite(latitude) && Number.isFinite(longitude);

// Map for placing a mender's pin precisely: drag the pin or click the map.
export function LocationPicker({ latitude, longitude, onChange }: Props) {
  const containerRef = useRef<HTMLDivElement>(null);
  const mapRef = useRef<maplibregl.Map | null>(null);
  const markerRef = useRef<maplibregl.Marker | null>(null);
  const onChangeRef = useRef(onChange);
  onChangeRef.current = onChange;
  const [showSatellite, setShowSatellite] = useState(false);
  const [isStyleLoaded, setIsStyleLoaded] = useState(false);

  useEffect(() => {
    if (!containerRef.current) return;

    const hasPin = hasCoordinates(latitude, longitude);
    const map = new maplibregl.Map({
      container: containerRef.current,
      style: STYLE_URL,
      center: hasPin ? [longitude, latitude] : [0, 20],
      zoom: hasPin ? PIN_ZOOM : OVERVIEW_ZOOM,
      attributionControl: { compact: true },
    });
    map.addControl(new maplibregl.NavigationControl({ showCompass: false }), 'top-right');

    const marker = new maplibregl.Marker({ draggable: true, color: '#0a0a0a' });
    if (hasPin) marker.setLngLat([longitude, latitude]).addTo(map);

    const placePin = (lngLat: maplibregl.LngLat) => {
      marker.setLngLat(lngLat);
      if (!marker.getElement().isConnected) marker.addTo(map);
      onChangeRef.current(lngLat.lat, lngLat.lng);
    };

    marker.on('dragend', () => placePin(marker.getLngLat()));
    map.on('click', (event) => placePin(event.lngLat));
    map.on('style.load', () => setIsStyleLoaded(true));

    mapRef.current = map;
    markerRef.current = marker;

    return () => {
      map.remove();
      mapRef.current = null;
      markerRef.current = null;
    };
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  // Follow coordinates typed into the latitude/longitude fields.
  useEffect(() => {
    const map = mapRef.current;
    const marker = markerRef.current;
    if (!map || !marker || !hasCoordinates(latitude, longitude)) return;

    const current = marker.getElement().isConnected ? marker.getLngLat() : null;
    if (current && current.lat === latitude && current.lng === longitude) return;

    marker.setLngLat([longitude, latitude]);
    if (!current) marker.addTo(map);
    map.easeTo({ center: [longitude, latitude], zoom: Math.max(map.getZoom(), PIN_ZOOM - 2) });
  }, [latitude, longitude]);

  useEffect(() => {
    const map = mapRef.current;
    if (!map || !isStyleLoaded) return;

    if (showSatellite && !map.getLayer(SATELLITE_LAYER_ID)) {
      if (!map.getSource(SATELLITE_SOURCE_ID)) map.addSource(SATELLITE_SOURCE_ID, SATELLITE_SOURCE);
      // Under the labels, so street names stay readable over the imagery.
      const firstSymbolLayer = map.getStyle().layers.find((layer) => layer.type === 'symbol');
      map.addLayer({ id: SATELLITE_LAYER_ID, type: 'raster', source: SATELLITE_SOURCE_ID }, firstSymbolLayer?.id);
    } else if (!showSatellite && map.getLayer(SATELLITE_LAYER_ID)) {
      map.removeLayer(SATELLITE_LAYER_ID);
    }
  }, [showSatellite, isStyleLoaded]);

  return (
    <div>
      <div className="relative h-72 overflow-hidden rounded-[0.625rem] border border-[#d5d5d5]">
        <div ref={containerRef} className="h-full w-full" />
        <div className="absolute left-2 top-2 flex overflow-hidden rounded-full border border-[#d5d5d5] bg-white text-xs shadow-sm">
          {[
            { label: 'Map', value: false },
            { label: 'Satellite', value: true },
          ].map((option) => (
            <button
              key={option.label}
              type="button"
              onClick={() => setShowSatellite(option.value)}
              aria-pressed={showSatellite === option.value}
              className={`px-3 py-1.5 transition-colors ${
                showSatellite === option.value ? 'bg-[#0a0a0a] text-white' : 'text-[#555] hover:bg-[#f5f5f5]'
              }`}
            >
              {option.label}
            </button>
          ))}
        </div>
      </div>
      <p className="mt-1.5 text-xs text-[#777]">Click the map or drag the pin onto the mender's exact door.</p>
    </div>
  );
}
